repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
      - id: trailing-whitespace
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-byte-order-marker
      - id: check-added-large-files
      - id: check-executables-have-shebangs

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.2
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: [--in-place]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]

  - repo: https://github.com/PyCQA/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        additional_dependencies: [pep8-naming]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982 # Do not update.
    hooks:
      - id: mypy
        exclude: tests/data/
        args: [--config-file=pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]

  - repo: https://github.com/qoomon/git-conventional-commits
    rev: v2.1.2
    hooks:
      - id: conventional-commits
